### ISSUE TITLE
any update ?

### ISSUE THREAD

**Issue by s3boun3t** [mkoskar/gtk-theme-mist#4]
hi, thanks for your theme
I would like to know if any updates are planned ?

thanks

**Comment by mkoskar** [comment]
I somehow missed this issue, sorry for such a late reply.

Sadly, I'm no longer actively using this theme because I hadn't had time to fix it really, and since I'm using minimal number (close to none) gtk3 apps I've put this to the bottom of my TODO stack :|.

**Comment by keithbowes** [comment]
@s3boun3t, you can use my fork if you want.  It more or less works in recent GTK+ versions.

@mkoskar, please feel free to merge my changes into your repo when you restart your work on it, if you don't want to reinvent the wheel.
